### ISSUE TITLE
複数のログ（実力センサと目標反力、とか）の異なるインデックスのデータを１つの図にプロットしたい

### ISSUE THREAD

**Issue by eisoku9618** [eisoku9618/kuroiwa_demos#28]
例えば

![aaa](https://cloud.githubusercontent.com/assets/4509039/11993949/8ecb0cba-aa7a-11e5-9c74-73a85edff6e9.png)

の上から二行目は

``` yaml
"left_foot_force":
  "log": ['rmfo_off_lfsensor', 'st_allRefWrench']
  "field": [[0,1,2,3,4,5]]
```

で2つのログを1つの図にプロットできているが、一行目と五行目は分かれてしまっていて見づらい。

``` yaml
"right_foot_force":
  "log": ['rmfo_off_rfsensor']
  "field": [[0,1,2,3,4,5]]

"RefWrench":
  "log": ['st_allRefWrench']
  "field": [[6, 7, 8, 9, 10, 11]]
```

のようにインデックスが異なるから。
